### ISSUE TITLE
希望能够提供设置选项，排除journal笔记

### ISSUE THREAD

**Issue by 0xlic** [TankCool/logseq-random-note#1]
因为journal里面基本上都是todo相关内容，希望能够只随机page，里面基本上都是知识点

**Comment by TankCool** [comment]
> 因为journal里面基本上都是todo相关内容，希望能够只随机page，里面基本上都是知识点

这的确是个不错的建议。

**Comment by TankCool** [comment]
新版本已经默认排除journal，有兴趣可以更新试试。

**Comment by ethinx** [comment]
抱歉，刚更新了1.0.1，然后发现 journal 给排除了。

不清楚现在 logseq 是否已经实现插件设置（虽然能看到有插件选项），可以的话后期设置成可选项吧，有的用户 :P 可能是在 journal 里面记录的，随机过去的日志也是有意思的事情

**Comment by TankCool** [comment]
> 抱歉，刚更新了1.0.1，然后发现 journal 给排除了。
> 
> 不清楚现在 logseq 是否已经实现插件设置（虽然能看到有插件选项），可以的话后期设置成可选项吧，有的用户 :P 可能是在 journal 里面记录的，随机过去的日志也是有意思的事情

因为暂时没有比较好的方案，看后面如果logseq提供图形界面的插件设置API的话会加上一些选项的。
