### ISSUE TITLE
feature suggestion: filter page-property

### ISSUE THREAD

**Issue by gujin03** [TankCool/logseq-random-note#4]
Thank you for your efforts.
This plug-in is very useful.
Each page has page-property in logseq,such as :
---------------------------
title:: this is tile
tags:: english
type:: book
---------------------------
I have 10 pages like above, Now I want to see the pages only in the 10 pages scope.
I wish you can add the feature through the pannel setting
like this:

{
  "disabled": false,
  "randomNoteIncludeJournals": true
"page-tags": english
}

thank you very much

**Comment by TankCool** [comment]
Thanks for the advice. I will take a look and make it happen.
