### ISSUE TITLE
1.0.5版本界面配置不生效

### ISSUE THREAD

**Issue by gujin03** [TankCool/logseq-random-note#5]
录制了一个动图，请作者修复一下，谢谢
![iShot2022-04-12_22 27 03](https://user-images.githubusercontent.com/38389059/162985471-46f5633f-0031-4e5e-b428-5761c9a219b6.gif)
补充说明：上图是在logseq-设置-插件设置里面是失效的，但是在本插件自身的配置界面又是可以的，两者不一致，希望统一一下。
![iShot2022-04-12_22 30 13](https://user-images.githubusercontent.com/38389059/162986243-e7ba3300-d0c5-4535-83ca-4c1388fefac1.gif)

**Comment by TankCool** [comment]
感谢你的反馈，这个貌似我本地没法复现出来。

这两个地方其实都是logseq根据插件调用的api来展示的，是从同一个地方获取的配置，只是展示在不同的地方。

可以尝试重启logseq或者在logseq的高级设置里面清理一下缓存看看能否正常。

**Comment by TankCool** [comment]
感谢你的反馈，这个貌似我本地没法复现出来。

这两个地方其实都是logseq根据插件调用的api来展示的，是从同一个地方获取的配置，只是展示在不同的地方。

可以尝试重启logseq或者在logseq的高级设置里面清理一下缓存看看能否恢复正常。
