### ISSUE TITLE
shortcut? 

### ISSUE THREAD

**Issue by PSEUDO-SAPPHO** [TankCool/logseq-random-note#6]
fast opening for the random pages would be necessary on my views, to start randomizing to catch appropriate note from  serendipity, i think shortcut in this case is very useful.

**Comment by TankCool** [comment]
Try `r n` , press key `r` then press key `n`.

`R`andom `N`ote, hope it works.

**Comment by tiankonganddahai** [comment]
Can the shortcut keys be adjusted to Ctrl/Alt/Shift+somekey or other customizable shortcut keys for users? 
It's too inconvenient to switch to another random page using the "r" and "n" method.
