### ISSUE TITLE
功能建议：一次点击同时呈现多个页面/块

### ISSUE THREAD

**Issue by lraieph0** [TankCool/logseq-random-note#7]
开发者你好，感谢开发这款好用的插件。

当笔记数量多到一定程度时，随机页面就有助于我回顾一些可能已经遗忘的笔记，这是我使用这款插件的初衷。

实际使用过程中，我遇到的情景是：十次点击，可能只有一两次出现的页面让我有兴趣回顾，也就是说，在这些点击中，负反馈的次数（点击，发现是不感兴趣的页面）大于正反馈次数（有兴趣回顾的页面），结果是我越来越不愿意去点击随机按钮，因为失望的预期总是大于期望。

在语雀中，我发现了一位叫临时哈桑的作者也提出了这个情况，他给出的解决方案是：一次随机呈现多个结果，这样子每次点击出现感兴趣内容的几率就大大提高，也能够在较少的点击次数下历遍所有笔记。具体来说，现有情况：1次点击出现1个结果；假如改进为：1次点击列出10个结果，这10个结果中只要出现了1个感兴趣的内容，这次点击就是有意义的，就是正反馈，而且只需十分之一次的点击就能浏览相同数量的笔记。

预想的展现方式
![image](https://user-images.githubusercontent.com/69003552/170422282-4ae1fb86-db9d-4dfe-a653-0ac48e3909fa.png)
左边仍然是1个具体页面，在右边栏中展现剩下9个结果。

如果开发者有兴趣的话，希望这些想法能为插件开发提供一些思路。

**Comment by TankCool** [comment]
感谢你的提议，这是一个非常不错的想法👍🏻，有时间的话会研究看看具体的实现。

**Comment by lraieph0** [comment]
发现插件已经实现了这个功能，感谢开发者快速又用心的更新！
